# Generated by Django 5.2.6 on 2025-09-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twetsapp', '0003_rename_tweet_twet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twet',
            options={'ordering': ['-created_at']},
        ),
    ]
