# Generated by Django 5.2.6 on 2025-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twetsapp', '0004_alter_twet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='twet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='twet_images/'),
        ),
    ]
