# Generated by Django 5.2.6 on 2025-09-30 19:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twetsapp', '0005_twet_description_twet_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twet',
            options={},
        ),
        migrations.AlterField(
            model_name='twet',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
